config/routes.rb
Blacksand::Engine.routes.draw do
  scope module: :dashboard do
    get '/' => 'pages#default'

    # TODO
    # resources :users

    resources :pages, except: [:show] do
      collection do
        get 'onchange_new'
        post 'sort'

        get 'children_partial'
        get 'search'
      end

      member do
        get 'onchange_edit'
        get 'get_prototype_id'
        get 'render_manage'
      end
    end

    resources :navigations do
      post :reorder, on: :collection
    end

    resources :templates, only: [:index]
    resources :prototypes, only: [:index, :show]
  end
end

app/controllers/blacksand/dashboard/base_controller.rb
module Blacksand
  class Dashboard::BaseController < ActionController::Base
    layout 'blacksand/dashboard'

    before_action :_authenticate!
    before_action :_authorize!

    helper_method :_current_user
    helper_method :visible?

    attr_reader :authorization_adapter

    private
    def _authenticate!
      instance_eval(&Blacksand.authenticate_with)
    end

    def _authorize!
      instance_eval(&Blacksand.authorize_with)
    end

    def _current_user
      instance_eval(&Blacksand.current_user_method)
    end

    def visible?(action, object)
      # 如果启用了授权
      if self.authorization_adapter
        return self.authorization_adapter.authorized?(action, object)
      end

      true
    end
  end
end

app/controllers/blacksand/dashboard/navigations_controller.rb
module Blacksand
  class Dashboard::NavigationsController < Dashboard::BaseController
    before_action :set_navigation, only: [:show, :edit, :update, :destroy]

    # GET /navigations
    # GET /navigations.json
    def index
      @navigations = Navigation.order(:position)
    end

    def reorder
      navigations = params[:navigations]
      navigations.each_with_index do |id, index|
        Navigation.update(id, {position: index})
      end

      respond_to do |format|
        format.json { render json: {success: true} }
        format.js { flash.now.notice = '保存成功' }
      end
    end

    # GET /navigations/1
    # GET /navigations/1.json
    def show
    end

    # GET /navigations/new
    def new
      @navigation = Navigation.new
    end

    # GET /navigations/1/edit
    def edit
    end

    # POST /navigations
    # POST /navigations.json
    def create
      @navigation = Navigation.new(navigation_params)

      respond_to do |format|
        if @navigation.save
          format.html { redirect_to navigations_url, notice: 'Navigation was successfully created.' }
          format.json { render :show, status: :created, location: [:dashboard, @navigation] }
        else
          format.html { render :new }
          format.json { render json: @navigation.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /navigations/1
    # PATCH/PUT /navigations/1.json
    def update
      respond_to do |format|
        if @navigation.update(navigation_params)
          format.html { redirect_to navigations_url, notice: 'Navigation was successfully updated.' }
          format.json { render :show, status: :ok, location: @navigation }
        else
          format.html { render :edit }
          format.json { render json: @navigation.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /navigations/1
    # DELETE /navigations/1.json
    def destroy
      @navigation.destroy
      respond_to do |format|
        format.html { redirect_to navigations_url, notice: 'Navigation was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_navigation
      @navigation = Navigation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def navigation_params
      params.require(:navigation).permit(:name, :url, :page_id, :position, :position, options: [ :hover_submenus, :link_sub_page ])
    end
  end
end

app/controllers/blacksand/dashboard/pages_controller.rb
module Blacksand
  class Dashboard::PagesController < Dashboard::BaseController
    before_action :set_page, only: [:show, :edit, :update, :destroy, :onchange_edit, :get_prototype_id]
    before_action :set_select, only: [:new, :edit, :onchange_new, :onchange_edit, :create, :update]

    def default
      redirect_to pages_url
    end

    def index
      @page = Page.where(id: params[:parent_id]).first
      @parent_id = params[:parent_id] || 0
      @all_children = Page.where(parent_id: nil).order(:position)
      @pages = @all_children.page(params[:page])

      # 编辑只能看到自己负责的板块
      tree_nodes = if false && current_user.role == 'editor'
                     Page.tree_nodes(current_user.page_ids)
                   else
                     Page.tree_nodes
                   end

      gon.pages = [{
                   text: '网站',
                   href: children_partial_pages_path(parent_id: nil),
                   page_id: 0,
                   nodes: tree_nodes,
                   }]

      # 选中父页面
      Page.selectNode(gon.pages, @parent_id.to_i)
    end

    def search
      # TODO: 查询排除自己
      @q = Page.ransack(params[:q])
      @pages = @q.result.page(params[:page])
    end

    def children_partial
      @page = Page.where(id: params[:parent_id]).first
      @parent_id = params[:parent_id]
      @parent_page = Page.find(params[:parent_id]) if params[:parent_id]
      @q = Page.includes(:template, :prototype).where(parent_id: params[:parent_id]).order(:position, created_at: :desc).ransack(params[:q])
      @all_children = @q.result
      @pages = @all_children.page(params[:page])
    end

    def show
    end

    def new
      @page = Page.new
      if params["parent_id"].present?
        @parent_id = params[:parent_id]
        parent_page = Page.find @parent_id
        @page.parent_id = params["parent_id"]

        # Set default template
        if parent_page.preferred_child_template_name
          @page.template = Template.find_by(name: parent_page.preferred_child_template_name)
        end

        # Set default prototype
        if parent_page.preferred_child_prototype_name
          prototype = Prototype.find_by(name: parent_page.preferred_child_prototype_name)
          @page.prototype = prototype
          prototype.fields.each do |field|
            Property.build_property(@page, field)
          end
        end
      end
    end

    def edit
      if !@page.properties.present? && @page.prototype.present?
        @page.build_properties
      end
    end

    def onchange_new
      @page = Page.new

      if params["parent_id"].present?
        @page.parent_id = params["parent_id"]
      end

      if params[:prototype_id].present?
        @page.prototype_id = params[:prototype_id]
        Prototype.find(params[:prototype_id]).fields.each do |field|
          Property.build_property(@page, field)
        end
      end
      render 'onchange_render'
    end

    def onchange_edit
      @page.properties.destroy_all
      if params[:prototype_id].present?
        @page.prototype_id = params[:prototype_id]
        @page.update_attributes(prototype_id: params[:prototype_id])
        @page.build_properties
        @page.save(validate: false)
      else
        @page.prototype_id = nil
        @page.update_attributes(prototype_id: nil)
      end
      render 'onchange_render'
    end

    def get_prototype_id
      respond_to do |format|
        format.json { render json: @page.prototype_id }
      end
    end

    def create
      @page = Page.new(page_params)

      respond_to do |format|
        if @page.save
          format.html { redirect_to pages_url(parent_id: @page.parent_id), notice: '页面创建成功.' }
          format.json { render :show, status: :created, location: @page }
        else
          puts @page.errors.full_messages
          format.html { render :new }
          format.json { render json: @page.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @page.update(page_params)
          format.html { redirect_to pages_url(parent_id: @page.parent_id), notice: '页面更新成功.' }
          format.json { render :show, status: :ok, location: @page }
        else
          format.html { render :edit }
          format.json { render json: @page.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @page.destroy
      respond_to do |format|
        format.html { redirect_to pages_url(parent_id: @page.parent_id), notice: '成功删除.' }
        format.json { head :no_content }
      end
    end

    def sort
      params[:page].each_with_index do |id, index|
        Page.update(id, {position: index+1})
      end
      render nothing: true
    end

    private
    def set_page
      @page = Page.find(params[:id])
    end

    def set_select
      @template_select = Template.all.map { |x| [x.name, x.id] }.sort_by {|x| x[0]}
      @prototype_select = Prototype.all.map { |x| [x.name, x.id] }
    end

    def page_params
      params.require(:page).permit(:title, :en_name, :parent_id, :template_id, :prototype_id, :content,
                                   :properties_attributes => [:id, :type, :field_id, :value, { values: [] }, :image, :file,
                                                              {:pictures_attributes => [:id, :name, :file, :_destroy]}])
    end

  end
end

app/controllers/blacksand/dashboard/prototypes_controller.rb
module Blacksand
  class Dashboard::PrototypesController < Dashboard::BaseController

    def index
      @prototypes = Prototype.all
    end

    def show
      @prototype = Prototype.find params[:id]
    end
  end
end

app/controllers/blacksand/dashboard/templates_controller.rb
module Blacksand
  class Dashboard::TemplatesController < Dashboard::BaseController

    def index
      @templates = Template.all
    end
  end
end

app/controllers/blacksand/dashboard/users_controller.rb
module Blacksand
  class Dashboard::UsersController < Dashboard::BaseController
    # layout 'manage'
    # load_and_authorize_resource
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /users
    # GET /users.json
    def index
      @users = User.normal
    end

    # GET /users/1
    # GET /users/1.json
    def show
    end

    # GET /users/new
    def new
      @user = User.new
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users
    # POST /users.json
    def create
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to dashboard_users_url, notice: t('user.user_save_success_notice') }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to dashboard_users_url, notice: t('user.user_edit_success_notice') }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_users_url, notice: t('user.user_delete_success_notice') }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :role, page_ids: [])
    end
  end
end

app/views/blacksand/dashboard/pages/_fields.html.erb
<% case f.object.field.field_type %>
  <% when 'image' then %>
    <%= f.file_field :image, filed_options(f) %>
    <%= f.form_group do %>
      <div class="row">
        <% if f.object.image? %>
          <div class="col-xs-6 col-md-3">
            <div class="thumbnail">
              <%= image_tag f.object.image_url %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% when 'slide' then %>
      <%= f.hidden_field :type %>
      <%= f.file_field :image, filed_options(f) %>
      <%= f.form_group do %>
          <div class="row">
            <% if f.object.image? %>
                <div class="col-xs-6 col-md-3">
                  <div class="thumbnail">
                    <%= image_tag f.object.image_url %>
                  </div>
                </div>
            <% end %>
          </div>
      <% end %>
<% when 'file' then %>
    <%= f.hidden_field :type %>
    <%= f.file_field :file, filed_options(f) %>
    <%= f.form_group do %>
        <div class="row">
          <% if f.object.file? %>
              <div class="col-xs-6 col-md-3">
                <a target="_blank" href="<%= f.object.file_url %>"><%= File.basename f.object.file.path %></a>
              </div>
          <% end %>
        </div>
    <% end %>
  <% when 'gallery' then %>
    <%= f.form_group label: {text: "#{f.object.field.description}", class: "#{'required' if f.object.field.required?}"} do %>
    <% end %>
    <%= f.hidden_field :type %>
    <%= f.fields_for :pictures do |picture| %>
      <%= render 'picture_fields', f: picture %>
    <% end %>

    <%= f.form_group nil, class: 'add-picture' do %>
        <%= link_to_add_association f, :pictures, 'data-association-insertion-node' => '.add-picture' do %>
            <i class="fa fa-plus"></i> 添加图片
        <% end %>
    <% end %>
  <% when 'array' then %>
    <%= f.form_group label: {text: "#{f.object.field.description}", class: "#{'required' if f.object.field.required?}"} do %>
    <% end %>
    <%= f.hidden_field :type %>
    <% f.object.values.each do |item| %>
        <div class="form-group array-item">
          <div class="col-md-offset-2 col-md-8">
            <%= text_field_tag "page[properties_attributes][#{f.options[:child_index]}][values][]", item, class: 'form-control' %>
          </div>
          <div class="col-md-2">
            <a class='btn btn-link btn-default btn-sm up-item-button'>上移</a>
            <a class='btn btn-link btn-default btn-sm remove-item-button'>删除</a>
          </div>
        </div>
    <% end %>

    <%= f.form_group nil, class: 'add-item' do %>
        <a class="add-item-button btn btn-link" data-child-index="<%= f.options[:child_index] %>">添加项目</a>
    <% end %>

  <% when 'rich_text' then %>
    <%= f.form_group label: {text: "#{f.object.field.description}", class: "#{'required' if f.object.field.required?}"} do %>
      <%= f.kindeditor :value, class: "rich_text" %>
      <br />
      <%= f.errors_on :value %>
    <% end %>
  <% when 'textarea' then %>
    <%= f.text_area :value, filed_options(f) %>
  <% when 'select' then %>
    <%= f.select :value, f.object.field.options.map{|e| [e, e]}, filed_options(f) %>
  <% when 'page' then %>
    <!-- page select2 -->
    <%= f.select :value, select_choices(f), filed_options(f), { data: { provide: 'page-select2' } } %>
  <% else %>
    <%= f.text_field :value, filed_options(f) %>
<% end %>

app/views/blacksand/dashboard/pages/_form.html.erb
<%= bootstrap_form_for @page, url: url, layout: :horizontal, html: { multipart: true } do |f| %>

  <%= f.select :prototype_id, @prototype_select, {:include_blank => true}, { :onchange => "onchange_render(this.value);", } %>
  <%= f.select :template_id, @template_select, {:include_blank => true} %>

  <!-- '无' 必须存在,要个 select2 allowClear 搭配使用才能生效 -->
  <% if @page.parent_id %>
      <%= f.select :parent_id, [['无', ''], [@page.parent.title, @page.parent_id]] %>
  <% else %>
      <%= f.select :parent_id, [['无', '']] %>
  <% end %>

  <%= f.text_field :title %>
  <%= f.text_field :en_name %>
	<%= f.fields_for :properties do |property_form| %>
    <%= render partial: 'fields', locals: {f: property_form} %>
    <%= property_form.hidden_field :field_id %>
	<% end %>
  <%= f.form_group label: { text: '内容' } do %>
      <%= f.kindeditor :content, :owner => @page %>
  <% end %>

  <%= f.form_group do %>
    <%= f.primary %>
  <% end %>
<% end %>

app/views/blacksand/dashboard/pages/_manage_list.html.erb
<% if @parent_id %>
    <div class="row m-v-10">
      <div class="col-md-12 m-b-10">
        <div class="row">
          <div class="col-md-8">
            <h4><%= @parent_page.title %></h4>
          </div>
          <div class="col-md-4 text-right" style="line-height: 39px;">
            <% if visible?(:edit, @parent_page) %>
              <%= link_to '编辑', edit_page_path(@parent_page) %> |
            <% end %>

            <% if visible?(:destroy, @parent_page) %>
              <%= link_to '删除', page_path(@parent_page), method: :delete, data: { confirm: '确定要删除吗?' } %> |
            <% end %>

            <a href="<%= Rails.application.routes.url_helpers.page_path(@parent_page) %>" target="_blank">
              <i class="glyphicon glyphicon-share"></i>预览
            </a>
          </div>
        </div>
      </div>

      <div class="col-md-12">
        <table class="table">
          <tr class="text-muted">
            <td> 标识: <strong><%= @parent_page.en_name %></strong></td>
            <td>模板: <strong><%= @parent_page.template.try(:name) %></strong></td>
            <td>原型: <strong><%= @parent_page.prototype.try(:name) %></strong></td>
            <td>子页面推荐模板: <strong><%= @parent_page.preferred_child_template_name %></strong></td>
            <td>子页面推荐原型: <strong><%= @parent_page.preferred_child_prototype_name %></strong></td>
          </tr>
        </table>
      </div>
    </div>
<% end %>

<div class="m-v-10">
  <% if visible?(:create, Blacksand::Page) %>
    <%= link_to new_page_path(parent_id: @parent_id), class: "btn btn-primary" do %>
        <i class="glyphicon glyphicon-plus"></i> 新增页面
    <% end %>
  <% end %>

  <% if visible?(:sort, Blacksand::Page) %>
    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal"><i class="glyphicon glyphicon-align-justify"></i> 排序</button>
  <% end %>
</div>

<div class="m-v-10">
  <%= search_form_for(@q, url: children_partial_pages_path, remote: true) do |f| %>
      <% if @parent_id.present? %>
          <%= hidden_field_tag :parent_id, @parent_id %>
      <% end %>
      <%= f.label :title_cont %>
      <%= f.text_field :title_cont %>
      <%= f.submit class: 'btn btn-primary btn-sm' %>
  <% end %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>标题</th>
      <th>标识</th>
      <th>模版</th>
      <th>原型</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each_with_index do |page, index| %>
    <tr>
      <th scope="row"><%= index+1 %></th>
      <td><%= page.title %>  </td>
      <td><%= page.en_name %></td>
      <td><%= page.template.try :name %></td>
      <td><%= page.prototype.try(:name) %></td>
      <td>
        <% if visible?(:edit, page) %>
          <%= link_to '编辑', edit_page_path(page) %> |
        <% end %>

        <% if visible?(:destroy, page) %>
          <%= link_to '删除', page_path(page), method: :delete, data: { confirm: '确定要删除吗?' } %> |
        <% end %>

        <a href="<%= main_app.page_path(page) %>" target="_blank">
          <i class="glyphicon glyphicon-share"></i>预览
        </a>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div id="paginator">
  <%= paginate @pages, :remote => true %>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">排序</h4>
      </div>
      <div class="modal-body">
        <p class="help-block">拖动排序</p>
        <ul id="modal-list" data-update-url="<%= sort_pages_path %>">
          <% @all_children.each do |p| %>
            <li data-id="<%= p.id %>"><%= p.title %></li>
          <% end %>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      </div>
    </div>
  </div>
</div>

app/views/blacksand/dashboard/pages/_picture_fields.html.erb
<div class="nested-fields">
  <hr>
  <%= f.text_field :name %>
  <%= f.file_field :file %>

  <%= f.form_group do %>
      <% if f.object.file.present? %>
          <%= image_tag f.object.file, class: 'img-responsive' %>
          <%= File.basename f.object.file.path %>
      <% end %>
  <% end %>

  <%= f.form_group do %>
    <%= link_to_remove_association f, class: 'btn btn-link' do %>
      <i class="fa fa-trash"></i> 删除
    <% end %>
  <% end %>
</div>

app/views/blacksand/dashboard/pages/children_partial.js.erb
$('#manage_list').html('<%= j render('manage_list') %>');

// 排序
dragula([$('#modal-list')[0]]).on('drop', function(){
  console.log('排序');

  var newOrders = $('#modal-list').children().map(function(){
        return $(this).data('id')
      })
      .get();

  var update_url = $('#modal-list').data('update-url');
  $.post(update_url, {page: newOrders})
});

app/views/blacksand/dashboard/pages/edit.html.erb
<div id="page_form">
	<%= render 'form', url: page_path(@page) %>
</div>

<script type="text/javascript">
var onchange_render = function(prototype_id) {
	if(window.confirm('更换原型将删除这个页面下的所有信息，确定要更换原型吗？')){
		$.ajax({
			url: "<%= onchange_edit_page_path(@page) %>" + "?prototype_id=" + prototype_id
		})
	} else {
		$.ajax({
			url: "get_prototype_id",
			dataType: "json"
		}).done(function(prototype_id) {
			$('#page_prototype_id').val(prototype_id)
		})
	}
}
</script>

app/views/blacksand/dashboard/pages/index.html.erb
<div class="row">
  <div class="col-md-3">
    <div id="manage_menu"></div>
  </div>
  <div class="col-md-9">
    <div id="manage_list">
    </div>
  </div>

</div>

<% content_for :javascript do %>
    <script>
      // 排序
      dragula([$('#modal-list')[0]]).on('drop', function(){
        console.log('排序');

        var newOrders = $('#modal-list').children().map(function(){
              return $(this).data('id')
            })
            .get();

        var update_url = $('#modal-list').data('update-url');
        $.post(update_url, {page: newOrders})
      });
    </script>
<% end %>

app/views/blacksand/dashboard/pages/new.html.erb
<ol class="breadcrumb" style="background-color: white;">
  <li><a href="<%= pages_path %>">页面列表</a></li>
  <li class="active">新增页面</li>
</ol>

<div id="page_form">
	<%= render 'form',  url: pages_path %>
</div>
<script type="text/javascript">
  // TODO: using url helper method
var onchange_render = function(prototype_id) {
  <% if params["parent_id"].present?  %>
    var url = "<%= onchange_new_pages_path(parent_id: params[:parent_id]) %>" + "&prototype_id=" + prototype_id;
  <% else %>
    var url = "<%= onchange_new_pages_path %>" + "?prototype_id=" + prototype_id;
  <% end %>

  $.ajax({ url: url });
}
</script>

app/views/blacksand/dashboard/pages/onchange_render.js.erb
$('#page_form').html('<%= j render partial: 'form', locals: { url: url_for_page(@page) } %>');

initSelect2();

KindEditor.create(
  'textarea[class="rich_text"]',
    {
      width: "100%",
      height: 300,
      allowFileManager: true,
      uploadJson: '/kindeditor/upload',
      fileManagerJson: '/kindeditor/filemanager'
    }
);

app/views/blacksand/dashboard/pages/show.html.erb
<h3><%= @page.title %></h3>

<%= link_to '编辑', edit_dashboard_page_path(@page) %>
<%= link_to '删除', dashboard_page_path(@page), method: :delete, data: { confirm: '确定删除吗?' } %>

<table class="table table-bordered">
  <caption>子页面</caption>
  <thead>
  <tr>
    <th>#</th>
    <th>标题</th>
    <th>标识</th>
    <th>模版</th>
    <th>原型</th>
    <th>操作</th>
  </tr>
  </thead>
  <tbody>
  <% @page.children.each_with_index do |page, index| %>
      <tr>
        <th scope="row"><%= index+1 %></th>
        <td><%= link_to page.title, dashboard_page_path(page) %></td>
        <td><%= page.en_name %></td>
        <td><%= page.template.name %></td>
        <td><%= page.prototype.try(:name) %></td>
        <td><%= link_to '删除', dashboard_page_path(page), method: :delete, data: { confirm: '确定要删除吗?' } %> |
          <%= link_to '编辑', edit_dashboard_page_path(page) %>
          | <%= link_to '子页面', children_dashboard_page_path(page) %>
        </td>

      </tr>
  <% end %>
  </tbody>
</table>